receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: info

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [logging]
    traces:
      receivers: [otlp]
      exporters: [logging]
