apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigate
spec:
  template:
    spec:
      containers:
      - name: apigate
        image: apigate:latest
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL